services:
  jenkins-docker:
    privileged: true
    container_name: jenkins-docker 
    image: docker:dind
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home 
    ports:
      - "2376:2376"
    networks:
      jenkins:
        aliases:
          - docker 

  jenkins-blueocean:
    environment:
      DOCKER_TLS_CERTDIR: /certs
      JENKINS_VERSION: ${JENKINS_VERSION:-2.516.2}
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    depends_on:
      - jenkins-docker 
    build: 
       dockerfile: Dockerfile 
       context: . 
    image: jenkins-blueocean:${JENKINS_VERSION:-2.516.2}
    container_name: jenkins-blueocean  
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home 
      - ${HOME:-${USERPROFILE}}:/data 
      - ${TMPDIR:-/tmp}:/forcopy 
    ports:
      - "8080:8080"
      - "50000:50000" 
    networks:
      - jenkins
networks: 
  jenkins: 
    name: jenkins
    driver: bridge  
    external: false 
volumes: 
   jenkins-docker-certs: {} 
   jenkins-data: {}
