---
- hosts: 'all'
  become: true

  tasks:
    - name:  Stop and Disable apache
      service:
        name: apache2
        state: stopped
        enabled: false 
    - name: Remove apache2
      apt:
        name: apache2
        update_cache: true
        state: absent
